sequence:
- event: LOGBOOK_ENTRY
  event_data:
    name: ALARM EVENT
    message: ALARM CODE RED
- execute_service: script.all_off
- delay:
    seconds: 3
- execute_service: notify.notify
  service_data:
    message: "ALARM CODE RED."
- execute_service: light.turn_on
  service_data:
    entity_id: light.rp2
    rgb_color: [255,0,0]
- execute_service: light.turn_on
  service_data:
    entity_id: light.jar_led
    rgb_color: [255,0,0]
- execute_service: light.turn_on
  service_data:
    entity_id: light.br_node_led
    rgb_color: [255,0,0]
- execute_service: light.turn_on
  service_data:
    entity_id: light.br_lifx
    rgb_color: [255,0,0]
    brightness: 255
- execute_service: light.turn_on
  service_data:
    entity_id: light.lr_door_color_lifx
    rgb_color: [255,0,0]
    brightness: 255
- execute_service: light.turn_on
  service_data:
    entity_id: light.lr_fireplace_color_lifx
    rgb_color: [255,0,0]
    brightness: 255