sequence:
- event: LOGBOOK_ENTRY
  event_data:
    name: EVENT
    message: "Welcome! Turning everything on."
- execute_service: alarm_control_panel.alarm_disarm
- execute_service: notify.notify
  service_data:
    message: "Welcome. It is daytime so keeping everything off!"
- execute_service: light.turn_off
  service_data:
    entity_id: light.lr_door_color_lifx
- execute_service: light.turn_off
  service_data:
    entity_id: light.lr_fireplace_color_lifx
- execute_service: light.turn_off
  service_data:
    entity_id: light.br_lifx
- execute_service: input_select.select_option
  service_data:
    entity_id: input_select.hyperion_effect
    option: "Off"