sequence:
- event: LOGBOOK_ENTRY
  event_data:
    name: EVENT
    message: "Low battery Event"
- execute_service: notify.notify
  service_data:
    message: "{% if states('sensor.ben_nexus_6p_battery') < '6'%}Low battery detected! Ben's battery is at {{states('sensor.ben_nexus_6p_battery')}}%{% else %} {% endif %} {% if states('sensor.cailin_nexus_6p_battery') < '6'%}Low battery detected! Cailin's battery is at {{states('sensor.cailin_nexus_6p_battery')}}%{% else %} {% endif %}"
- execute_service: light.turn_on
  service_data:
    entity_id: light.br_node_led
    rgb_color: [255,0,0]