sequence:
- event: LOGBOOK_ENTRY
  event_data:
    name: EVENT
    message: Good Morning! The sun hasn't risen yet so lets turning some lights on. 
- execute_service: notify.notify
  service_data:
    message: "Good Morning! The sun isn't up yet so lets turn on some lights."
- execute_service: switch.turn_off
  service_data:
    entity_id: switch.bedroom_fan
- execute_service: light.turn_on
  service_data:
    entity_id: light.br_lifx
    brightness: 80
    color_temp: 233
    transition: 10
    rgb_color: [255,255,255]
- execute_service: light.turn_on
  service_data:
    entity_id: light.lr_door_color_lifx
    brightness: 80
    color_temp: 233
    transition: 10
    rgb_color: [255,255,255]
- execute_service: light.turn_on
  service_data:
    entity_id: light.lr_fireplace_color_lifx
    brightness: 80
    color_temp: 233
    transition: 10
    rgb_color: [255,255,255]
- delay:
    minutes: 2
- execute_service: light.turn_on
  service_data:
    entity_id: light.br_lifx
    brightness: 255
    color_temp: 233
    transition: 10
    rgb_color: [255,255,255]
- execute_service: light.turn_on
  service_data:
    entity_id: light.lr_door_color_lifx
    brightness: 255
    color_temp: 233
    transition: 10
    rgb_color: [255,255,255]
- execute_service: light.turn_on
  service_data:
    entity_id: light.lr_fireplace_color_lifx
    brightness: 255
    color_temp: 233
    transition: 10
    rgb_color: [255,255,255]