sequence:
- event: LOGBOOK_ENTRY
  event_data:
    name: EVENT
    message: "Restarting Home Assistant"
- execute_service: notify.notify
  service_data:
    message: "Restarting Home Assistant at {{ states('sensor.date__time') }}"
- execute_service: shell_command.restart_ha