sequence:
- event: LOGBOOK_ENTRY
  event_data:
    name: EVENT
    message: SUNRISE blinds open
- execute_service: notify.notify
  service_data:
    message: "The sun is up and the kitchen and living room blinds are open!"
- execute_service: switch.turn_on
  service_data:
    entity_id: switch.livingroom_blinds
- execute_service: switch.turn_on
  service_data:
    entity_id: switch.kitchen_blinds