alias: "Alarm Set Sleeping"
trigger:
  - platform: state
    entity_id: input_select.ben_status
    state: "sleeping"
  - platform: state
    entity_id: input_select.cailin_status
    state: "sleeping"
condition:
  - platform: state
    entity_id: input_select.company
    state: "disabled"
action:
  service: script.alarm_home