alias: "Away"
trigger:
  - platform: state
    entity_id: group.all_devices
    from: "home"
    to: "not_home"
condition:
  - platform: template
    value_template: "{% if states('input_select.ben_status') != 'sleeping' and states('input_select.cailin_status') != 'sleeping' %}true{% else %}false{% endif %}"
  - platform: state
    entity_id: input_select.company
    state: "disabled"
action:
  service: script.all_off