alias: "Morning bedroom blinds open, fan off"
trigger:
  - platform: state
    entity_id: input_select.ben_status
    from: "sleeping"
    to: "standby"
  - platform: state
    entity_id: input_select.cailin_status
    from: "sleeping"
    to: "standby"
  - platform: sun
    event: sunrise
    offset: "+00:05:00"
condition:
  - platform: state
    entity_id: group.all_devices
    state: "home"
  - platform: state
    entity_id: sun.sun
    state: "above_horizon"
  - platform: template
    value_template: "{% if states('input_select.ben_status') != 'sleeping' and states('input_select.cailin_status') != 'sleeping' %}true{% else %}false{% endif %}"
  - platform: state
    entity_id: input_select.company
    state: "disabled"
action:
  service: script.morning