alias: "Sunset, all on, cloudy"
trigger:
  platform: sun
  event: sunset
  offset: "-01:30:00"
condition:
  - platform: numeric_state
    entity_id: sensor.weather_cloud_coverage
    above: 70
  - platform: state
    entity_id: group.all_devices
    state: "home"
action:
  service: script.all_on