alias: "Sunset, blinds closed, not cloudy"
trigger:
  platform: sun
  event: sunset
  offset: "-00:30:00"
condition:
  - platform: numeric_state
    entity_id: sensor.weather_cloud_coverage
    below: 70
action:
  service: script.sunset